module.exports = {
  extends: ['plugin:@angular-eslint/template/recommended'],
  rules: {
    '@angular-eslint/template/attributes-order': ['error', { alphabetical: true }],
    '@angular-eslint/template/banana-in-box': 'error',
    '@angular-eslint/template/conditional-complexity': 'error',
    '@angular-eslint/template/cyclomatic-complexity': ['error', { maxComplexity: 10 }],
    '@angular-eslint/template/elements-content': 'error',
    '@angular-eslint/template/eqeqeq': 'error',
    '@angular-eslint/template/label-has-associated-control': 'error',
    '@angular-eslint/template/mouse-events-have-key-events': 'error',
    '@angular-eslint/template/no-any': 'error',
    '@angular-eslint/template/no-autofocus': 'error',
    '@angular-eslint/template/no-call-expression': 'error',
    '@angular-eslint/template/no-distracting-elements': 'error',
    '@angular-eslint/template/no-duplicate-attributes': 'error',
    '@angular-eslint/template/no-interpolation-in-attributes': 'error',
    '@angular-eslint/template/no-negated-async': 'error',
    '@angular-eslint/template/no-positive-tabindex': 'error',
    '@angular-eslint/template/prefer-self-closing-tags': 'error',
    '@angular-eslint/template/role-has-required-aria': 'error',
    '@angular-eslint/template/table-scope': 'error',
    '@angular-eslint/template/use-track-by-function': ['error', { alias: ['trackByIndex', 'trackByProperty'] }],
    '@angular-eslint/template/valid-aria': 'error',
  },
};
